#version: "3.8"
services:
  mysqldb:
    container_name: mysql-demo-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
    networks:
      springboot-mysql-net:

  springboot-restful-microservices:
    container_name: springboot-restful-webservices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:
